//
//  MenuModels.swift
//  PizzaMenu
//
//  Created by Анастасия Беспалова on 11.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct DisplayedItem
{
    var name: String
    var price: Int
    var composition: String
    var img: UIImage?
    var category: Categories
    
    init(rawItem: ItemRaw, image: UIImage?) {
        self.name = rawItem.name
        self.price = Int(rawItem.price) ?? 0
        self.composition = rawItem.composition
        self.category = rawItem.category
        self.img = image
    }
    
    
}

enum Menu
{
    
    enum FetchItems
    {
        struct Request
        {
        }
        struct Response
        {
            var displayedItems: [DisplayedItem]
        }
        struct ViewModel
        {
            var displayedItems: [DisplayedItem]
            
        }
    }
}
